@url = http://localhost:5000/api/v1/role

### GET ALL 
GET {{url}}?limit=2&page=1

### GET BY ID
GET {{url}}/63bffa430fd6f6d8d3f95dd7

### CREATE 
POST {{url}}
Content-Type: application/json

{
    "name": "Quản trị viên 5",
    "key": "ADMIN 5"
}

### UPDATE 
PATCH {{url}}/63c121473f0914739b5c3184
Content-Type: application/json

{
    "name": "Quản trị viên 6",
    "key": "ADMIN 5"
}

### DELETE
DELETE {{url}}/63bffa430fd6f6d8d3f95dd7

### DELETE
DELETE {{url}}/force/63bffa430fd6f6d8d3f95dd7
